# Generated by Django 5.2.1 on 2025-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviereport_favorite_hiddenmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
